### ISSUE TITLE
Project location for download

### ISSUE THREAD

**Issue by adonisc** [hybridgroup/cylon-raspi#30]
Hi! i was about to install the cyclon-raspi framework but fails showing 404 error this thru NPM and on github. If you can provide the file again thanks in advance! by the way im downloading thru an RPi

**Comment by deadprogram** [comment]
Hi @adonisc seems fine on https://www.npmjs.com/package/cylon-raspi perhaps you were having a network problem?

**Comment by adonisc** [comment]
Yes it seems the package there but it was throwing that it was marked as
moved permanently and/or not found errors (403,404) i will try again today.

Thanks for the quick answer!!!

**Comment by adonisc** [comment]
Hi, i don't know if i'm doing anything wrong but can't download thru npm it continues throwing 404 error :(

**Comment by deadprogram** [comment]
Is your raspi able to access other npm packages?

**Comment by deadprogram** [comment]
can we get a look at your package.json? or are you just using the npm command directly?

**Comment by adonisc** [comment]
Thanks Ron i already manage the problem i already using cylon! Thanks a lot
for your help.

**Comment by deadprogram** [comment]
Glad to hear it!
