### ISSUE TITLE
driver: 'led' toggles every start from crashing to working

### ISSUE THREAD

**Issue by tbarteit** [hybridgroup/cylon-raspi#35]
When I run the led demo from the git page, nodejs crashes every first run.
On the second run it works perfectly. On the third run it crashes again and so on.
It toggles every time, from crashing to working.

Update:
Same for node: v0.12.9 and npm: 2.14.9

I am using:

``` bash
Hardware: Raspberry Pi 2
OS: RASPBIAN JESSIE 4.1 (2015-11-21)
Firmware: 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux
NodeJS: v0.10.29 (Stock)
NPM: 1.4.21
```

Install and run:

``` bash
npm install cylon cylon-raspi cylon-gpio cylon-i2c
node cylon_test_led.js
```

cylon_test_led.js:

``` javascript
var Cylon = require("cylon");

Cylon.robot({
  connections: {
    raspi: { adaptor: 'raspi' }
  },

  devices: {
    led: { driver: 'led', pin: 38 }
  },

  work: function(my) {
    every((1).second(), my.led.toggle);
  }
}).start();
```

error-msg:

``` bash
node cylon_test_led.js
2016-01-05T14:06:41.748Z : [Robot 1] - Starting connections.
2016-01-05T14:06:41.804Z : [Robot 1] - Starting connection 'raspi'.
2016-01-05T14:06:41.811Z : [Robot 1] - Starting devices.
2016-01-05T14:06:41.812Z : [Robot 1] - Starting device 'led' on pin 38.
2016-01-05T14:06:41.813Z : [Robot 1] - Working.

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at DigitalPin.emit (events.js:74:15)
    at DigitalPin._setModeCallback (/home/pi/Share/testDir/1_npmTest/node_modules/cylon/lib/io/digital-pin.js:152:17)
    at DigitalPin.<anonymous> (/home/pi/Share/testDir/1_npmTest/node_modules/cylon/lib/io/digital-pin.js:146:10)
    at fs.js:953:21
    at Object.oncomplete (fs.js:107:15)
```

**Comment by deadprogram** [comment]
That looks to me like kind of permissions problem when first trying to create the `export` file that contains the GPIO pin mappings. Can you please run `whoami` and also `groups` commands, and provide the output of both?

**Comment by subjaeger** [comment]
"whoami" -> "pi" 
"groups" -> "pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi"

**Comment by deadprogram** [comment]
And do you have any udev rules setup?

**Comment by subjaeger** [comment]
No, I didn't. It is basically still the stock firmware. Besides "apt-get upgrade".
The odd thing is that is is working... every 2nd start of the script.

**Comment by deadprogram** [comment]
I suggest you try to follow the steps on https://github.com/hybridgroup/cylon-raspi#connecting-to-raspberry-pi-gpio to correct permissions problems. This is a common requirement on pretty much any Linux GPIO.

Please give that a try, and let us know how it goes.

**Comment by deadprogram** [comment]
Hi, @subjaeger were you able to try setting the udev rules as described in the README?

**Comment by deadprogram** [comment]
Hi @tbarteit were you able to get past your issue?

**Comment by mvpSergio** [comment]
hi, im follow the cylon.js LED using RPI tutorial but the program does't run, and I follow all the instruction.
 I have a RPI 3 model B, and i use this code

script.js:

```
var Cylon = require("cylon");

Cylon.robot({
  connections: {
    raspi: { adaptor: 'raspi' }
  },

  devices: {
    led: { driver: 'led', pin: 11 }
  },

  work: function(my) {
    every((1).second(), my.led.toggle);
  }
}).start();
```

so when i try to run my programs using 

```
npm install cylon cylon-raspi cylon-gpio cylon-i2c
node script.js
```

and follow all the instruction for the installation
the program throw this error 

error-msg:
```
pi@piSystem:~/Cylon$ node script.js 
2017-07-19T04:52:37.293Z : [Robot 1] - Starting connections.
2017-07-19T04:52:37.322Z : [Robot 1] - Starting connection 'raspi'.
2017-07-19T04:52:37.326Z : [Robot 1] - Starting devices.
2017-07-19T04:52:37.326Z : [Robot 1] - Starting device 'led' on pin 11.
2017-07-19T04:52:37.326Z : [Robot 1] - Working.

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at DigitalPin.EventEmitter.emit (events.js:74:15)
    at DigitalPin.<anonymous> (/home/pi/Cylon/node_modules/cylon/lib/io/digital-pin.js:117:12)
    at fs.js:944:21
    at Object.oncomplete (fs.js:107:15)
```

tnks for your time, and i wait your answer

**Comment by hellnano** [comment]
did you try using `SUDO` before your commands? ( like `sudo node scripts.js` ) ... if this "solve" the problem, then you need to check your permissions .

**Comment by warlock** [comment]
Not resolved.
